### ISSUE TITLE
Enhancement Requests | Propelling Code Snippets to New Heights

### ISSUE THREAD

**Issue by ghost** [sheabunge/code-snippets#107]
**Good Day!**

Your plugin is awesome and have been using it for several years. 

Based on our usage, we'd like to submit several enhancement requests that will add value and an impressive "wow" factor to it. 

They are:

**(1) Add a "[Return to Snippets](https://prnt.sc/10i4h4l)" button to the top section of each individual snippet.** 

When clicked, the user is taken back to "All Snippets." Currently, there's no way to return to "All Snippets" without hitting the browser's back button or clicking the plugin's corresponding menu item.

**(2) Add a new Screen Options column titled "[Item](https://prnt.sc/10i4qfg)".** 

This new column will help developers or users sequence their added snippets at will. When activated, it would be the first column displayed under "All Snippets" and the user will be able to add a sequential number next to each snippet. Most useful when a website is using 10+ snippets. It will help users list their snippets in a sequential order - independent of the ID and Priority columns.

**(3) Change the "[Modified](https://prnt.sc/10i4yic)" column display format to [WordPress' Date and Time format](https://prnt.sc/10i50rg).**

This change will offer the user Date and Time options that currently don't exist in the plugin. It also allows users to select a format that is commensurate with their country's format.

Hoping the above makes sense and can be integrated into your plugin.

Thank you!

**Comment by Jetxpert** [comment]
Good Day!

Updates:

(1) No change. Looking forward to your plugin update incorporating this enhancement.

(2) Perhaps it would be best to delete the column titled, "Priority", and instead add a new first column titled, "Item" or "Item No.". Entries under "Item" or "Item No." would be unique (i.e., 1, 2, 3, etc.). This will allow both users and you (developer) to quickly reference a code snippet under review or discussion. Also, as mentioned in (2)(b) above, it would be helpful to add drag-and-drop or arrow up/down capabilities to your plugin to allow sorting of the snippets.

(3) On second thought, not sure the "ID" and "Modified" columns have much value. We hardly use the information provided by these column. I say, delete them.

Thanks for your help!

**Comment by sheabunge** [comment]
Hi @Jetxpert,

I'll make sure the All Snippets button is there in the next release, as long as it doesn't get in the way of other interface changes.

If you don't find the modified or id columns useful, you should be able to hide them using the Screen Options tab.
