### ISSUE TITLE
site crashed

### ISSUE THREAD

**Issue by 8mmraipur** [sheabunge/code-snippets#116]
my site is crashed as i inserted a wrong php code. now it is in recovery mode. im not able to use the plug in to delete that specific code, it is asking me delete all of the plug in itself. i have many codes installed already which are important and i dont remember all of them

please let me know a solution

**Comment by sheabunge** [comment]
Code Snippets v3 Pro will include support for CSS snippets.

Until then, you can embed CSS in a PHP snippet like this:

```php
add_action( 'wp_head', function () { ?>
<script>

/* css code here */

</script>
<?php } );
```
