### ISSUE TITLE
Site Health Debug Information for Code Snippets

### ISSUE THREAD

**Issue by sc0ttkclark** [sheabunge/code-snippets#117]
As a plugin developer/support member,
I want to know what code snippets customers use on their site,
So I can see their code snippet titles are and where they loads (admin/front),
And I can provide them with more detailed support by identifying snippets that might be causing a problem.

**Comment by VerdiH** [comment]
Never mind my last email, I got it now. Seems like a feature for Pro,
correct?

Kind regards,

Verdi Heinz

+31 0623767953 <+31+0623767953>
***@***.***
https://ver3.pro
Book a meeting <https://meet.ver3.pro/en/e/verdi>
