### ISSUE TITLE
Please add information on how to report security issues

### ISSUE THREAD

**Issue by kazet** [sheabunge/code-snippets#120]
Hi,

I would like to report a security vulnerability. I don't want to create a Github issue for obvious reasons. Please let me know where to report (e.g. by adding relevant information to the repo).

Best,
Krzysztof Zając

**Comment by sheabunge** [comment]
Hi Krzysztof,

Great idea, this is definitely something we should have visible.

I've added this page: https://github.com/sheabunge/code-snippets/security/policy
