### ISSUE TITLE
Want to debug/explore snippet defined variables

### ISSUE THREAD

**Issue by shahzaib3311** [sheabunge/code-snippets#121]
I Want to debug/explore snippet defined variables to show what data those variables are in snippet holding but unfortunately, I'm unable to see log/dump as its PHP code. Need help in printing variables for debugging purposes. Suppose I've a snippet activated 
`function action_woocommerce_checkout_order_processed( $order_id, $posted_data, $order ) { /* $hello = "Hi User"*/}` I want to see $hello value when this snippet will be triggered.

**Comment by sheabunge** [comment]
If you are using an action hook, you should be able to just `var_dump()` to the page output.

Otherwise, you can pick an appropriate action hook for general data. I like to use `admin_footer_text`.
