### ISSUE TITLE
Enabling some common functionality and shortcuts

### ISSUE THREAD

**Issue by karmaral** [sheabunge/code-snippets#125]
Hello!
I spend quite some time in your code editor, and I dearly miss some basic functionalities of my (or any, I'd argue) regular IDE.
These are: 
- `Ctrl + /` for comments
- `Alt + Up/Down` for swapping lines
- Code folding
- Vim keybindings

So far I managed to enable the first three no problem in a fork. I still have to dig in a little deeper regarding the custom keymaps.
Would these features be welcome if added?

Cheers

**Comment by sheabunge** [comment]
Hi @karmaral,

That sounds super useful. Please feel free to create a PR with any changes to the existing keymap you think might be generally useful.

Also, I'm sure you're already across this, but the docs for the CodeMirror editor we are using has a section all about the different keymap options which should be useful: https://codemirror.net/doc/manual.html#keymaps

**Comment by karmaral** [comment]
Alright, great!
Yeah, I was aware of that, it's just that the last time I wanted to add the keymaps manually into an npm setting I had issues with it. It seems they're already included in here so it is just a matter of exposing them. I'll open a PR soon with everything and we can take it from there.

**Comment by sheabunge** [comment]
It's not a problem to add extra npm packages if you need them. The plugin has a build script that can grab the relevant parts and bundle it together for distribution on wordpress.org

**Comment by karmaral** [comment]
Ok, so I was cleaning everything up, and suddenly it stopped working. I can't tell if it was after running the `package` command or what, but now Wordpress is not recognizing the plugin, even if I clone it from a clean fork. I'm really confused... have you ever had this issue?

I'll continue troubleshooting anyway.

**Comment by karmaral** [comment]
Strange. It seems the lines `Author | Author URI` were duplicated in `code-snippets.php` and they were overriding `Plugin Name | Plugin URI`.
Reverting this fixes my issue, but I'm not sure how it managed to work on the first place before this. Anyways....

**Comment by karmaral** [comment]
@sheabunge Let me know your thoughts on the PR when you can.

**Comment by sheabunge** [comment]
Closing this as the PR is merged. Thank you again!
