### ISSUE TITLE
This plugin has been closed as of May 4, 2022 and is not available for download. This closure is temporary, pending a full review.

### ISSUE THREAD

**Issue by mxdpeep** [sheabunge/code-snippets#127]
Wordpress.com removed this plugin from its directory due to a possible security vulnerability.

https://wordpress.org/support/topic/pending-a-full-review/

**Comment by xmontana** [comment]
You can read the explanation of this incident in [this thread](https://wordpress.org/support/topic/pending-a-full-review/#post-15618659).

**Comment by sheabunge** [comment]
We are working on having it restored as soon as possible
