### ISSUE TITLE
Plugin removed from WordPress - Security Vulnerability?

### ISSUE THREAD

**Issue by mblais** [sheabunge/code-snippets#128]
WordFence reports as of May 5 that Code Snippets has been removed from WordPress and 2.14.3 has an "unpatched security vulnerability":

![image](https://user-images.githubusercontent.com/281745/167280751-7252c67e-9781-46e5-b223-dc2626cbaf66.png)

I can't find any additional info about this – Can anyone elucidate?

**Comment by spk100** [comment]
This post might shed some light

https://wordpress.org/support/topic/pending-a-full-review/#post-15618659

**Comment by sheabunge** [comment]
See #127.
