### ISSUE TITLE
Ideas for the "Cloud Storage" & "Cloud Snippets" features

### ISSUE THREAD

**Issue by deckerweb** [sheabunge/code-snippets#136]
Just a few thoughts and suggestions for your upcoming cloud features. Really don't know what you're planning and working on (totally fine so). If you feel this doesn't belong here in public feel free to delete, I have no problem with that. But maybe I am overseeing something or my perspective on this might be that it could not be technically done – therefore I am posting here for a bit of serious discussion.

The features I would dream of with Code Snippets and connection to some cloud:

**1) Central Dashboard**
My account dashboard where I see an overview table of all my snippets with title and date added and date last edited, plus the sites/instances this snippet is in use. Plus a toggle to deactivate this snippet overall: deactivate on all active sites for example.

**2) Able to edit/update snippet in the cloud:**
I could edit any snippet in the cloud (just like Gists by Github...) and optionally decide to update all existing instances/sites this snippet is active.

**3) folders & tags:**
Organize in folders and have tagging available for filtering huge collections. Search is mandatory anyways.

**4) export/import:**
I would be able to import/export via .json files like within the plugin itself. Would make sense to add compatibility to your competitors for export/import snippets if technically possible (Advanced Scripts; Scripts Organizer; WPCodeBox).

**5) Manage sites – push/pull snippets:**
I can decide which selected snippets or selected folder or selected tag I push to a newly connected site for example. – Or the opposite way: In a newly setup WP site I decided to pull a certain folder/tag etc. of snippets into this site.

**6) repository feature:**
I decide which selected snippets I suggest for a "global community snippet repository". These snippets need to be scanned for security but after that I would have the option to insert snippets in my WP site from such a community cloud repository (similar to the "Repository" that is available in your competitor "WPCodeBox" currently).

I know this all sounds a lot. Would be a dream come true for me and could end the use of some desktop code snippet app for sure... It is clear that such features would need a lot of time and effort. Maybe some of this or even all would make some sense and maybe also for your business model. Really don't know but would like to get some feedback if these ideas really could become "a thing" someday?

**Comment by sheabunge** [comment]
Thank you for these suggestions! I doubt that the first implementation of our cloud feature will contain all of these, but it's very helpful to know what people are looking for ideally and then setting our trajectory and deciding how to work up to that step by step.
