### ISSUE TITLE
Adding a CSS tab

### ISSUE THREAD

**Issue by paaljoachim** [sheabunge/code-snippets#138]
Hey

Where is the CSS tab....?
![Screenshot 2022-07-17 at 22 53 05](https://user-images.githubusercontent.com/5323259/179424472-8eb4d872-6380-49c9-9ad6-6dc1a04a1c30.jpg)

Here it is.... In my mockup.
![Code snippets CSS tab](https://user-images.githubusercontent.com/5323259/179424613-9faa0427-0eda-4fcb-b066-9c2c4451aed3.jpg)

I run a WordPress tutorial site and use PHP and CSS for explaining features to users.

Let's say that I use the default theme Twenty Twenty Two (Full Site Editing).
The Customize link is removed from the Appearance menu. So no Customize section, and no child theme to open the style.css and add modifications to.

So to make it easy for the user to add CSS where it is needed I decided to use https://wordpress.org/plugins/custom-codes/  as it offers PHP and custom CSS adjustments in one plugin. But I have had sites crash on me because of code snippets I have added using the plugin. 

What I really would like to see the Code Snippets plugin make CSS more available to use.
it would be very helpful to have a CSS tab in Code Snippets plugin. The added bonus creating more visibility is that I can stick to Code Snippets plugin when I show custom PHP and CSS.

Thanks!

**Comment by sheabunge** [comment]
It's in Code Snppets Pro :) 

http://codesnippets.pro/

**Comment by sheabunge** [comment]
How would you envision the split between Free and Pro features?

We do try and have a divide like that already, with Functions and basic Content snippets in Free, and CSS and JS in Pro.

**Comment by paaljoachim** [comment]
Code snippets from my own experience usually are PHP or CSS. When a plugin is called Code snippets I would expect these two features in place in a free version. Giving me the chance to use both. As I use the plugin I might gradually begin looking at what the pro version offers. Because when there is a plugin that is really helpful I will look at how I can contribute be it through testing, purchasing the pro version or other ways. 

Companies who count on various plugins will likely purchase the plugins they need as they know these are supported on the long run. Individuals or freelancers might go with the free plugins because their budget is much less.

The thing is that you want people to download and use your free plugin.
Which means you want it to be the go to plugin for adding code customizations for a WordPress site. 
There are various plugins that offer one or the other customizations.

Doing a quick search here: https://wordpress.org/plugins/search/code+snippets/

Insert PHP Code Snippet allows you to create shortcodes corresponding to PHP code snippets.
https://wordpress.org/plugins/insert-php-code-snippet/

Offers: CSS or JS code snippets
https://wordpress.org/plugins/easy-code-snippets/

Here is one I got to test out:
The Code Manager allows WordPress users to write, test and deploy PHP, JavaScript, CSS and HTML code blocks from the WordPress dashboard. https://wordpress.org/plugins/code-manager/

I mention the above as there are different needs. But for me it goes back to the most basic snippets one wants to add.
PHP and CSS.


Going through the Features comparison list. CSS.
This should be free: Create CSS styles for the admin or front-end and Built-in autocomplete and code linting.
The rest in the CSS list continue in the Pro plugin.

The Pro plugin offers so many upgraded experiences that many will go ahead and purchase the Pro. As I said companies are count on plugins staying around for a longer period of time will very likely purchase the plugin.

I would suggest that various people who in one way or another should be able to contact you or Verdi and get a coupon (in addition to the launch offer). Especially now with the new Pro plugin, as you want tutorial authors and others to use both and compare. Get these important folks to use the Pro plugin and promote in through tutorials and articles. I will send you an e-mail.

**Comment by sheabunge** [comment]
You can still use CSS snippets in the free version, you just need to wrap them in `admin_head` or `wp_head` hooks. The Pro version just improves on this with the additional snippet type, code concatenation and minification, browser caching, etc.

When we started developing the Pro version, we had to make a decision about which types to include in the free plugin, and we decided that Functions and Content snippets would be the most generally useful.

It's definitely possible that some of the Pro features will make their way into free eventually, but we don't have any concrete plans on what that will look like at this stage.

We're definitely interested in potential collaborations. Contact us through our [help center](https://help.codesnippets.pro/) for more details.
