### ISSUE TITLE
highlighting existing code-snippets (code blocks)

### ISSUE THREAD

**Issue by gbyat** [sheabunge/code-snippets#141]
the last update and later upgrade to pro destroyed all my published code snippets highlighted by "Syntax-highlighting Code Block (with Server-side Rendering)". so I had to disable the plugin "Syntax-highlighting Code Block (with Server-side Rendering)" - makes me sad because it was the best code highlighting plugin ever used and made no performance-problems, now all my published code snippets are plain :(. it would be great to optionally highlight codeblocks (automatically global, not one by one, so it's possible to get the highlights back that went lost) - I know, code snippets pro can be used to publish code snippets also, but have hundreds of them published already. - the other way would be: leave the wp code block alone, so that highlighting plugins continue doing their jobs. - thanks in advance.

**Comment by sheabunge** [comment]
Hello @gbyat,

If you use the Code Snippets Source shortcode, editor block or elementor widget to publish your snippets, then they should be highlighted by the built-in highlighter. We don't modify any existing code blocks or widgets, just add an additional one you can optionally use.

**Comment by sheabunge** [comment]
Closing this for now, as there's not much we can do without further information.
