### ISSUE TITLE
Code Snippets broke my site

### ISSUE THREAD

**Issue by mauricemaurer** [sheabunge/code-snippets#167]
Hi,

    I added a code snippet that broke my website.
    I deleted the snippet from the database directly (did not know about safe mode).
    Site was still broken (only when Code Snippets plugin active)
    I deleted Code Snippets plugins and reinstalled it
    Site was still broken (only when Code Snippets plugin active)
    I reverted to a previous backup before I added the snippet
    Site is still broken (only when Code Snippets plugin active)
    I activated in wp-config define( 'CODE_SNIPPETS_SAFE_MODE', true );
    Now the page loads again and I can enter Code snippets but the snippet that broke everything is not there. If I deactivate the Safe mode the page is broken again

Any ideas? If I cant figure this out I cannot use code snippets. The snippet that broke the page is this one (from WC Product Tables):
<?php
/**
* The Template for displaying product archives, including the main shop page which is a post type archive
*
* This template can be overridden by copying it to yourtheme/woocommerce/archive-product.php.
*
* HOWEVER, on occasion WooCommerce will need to update template files and you
* (the theme developer) will need to copy the new files to your theme to
* maintain compatibility. We try to do this as little as possible, but it does
* happen. When this occurs the version of the template file will be bumped and
* the readme will list any important changes.
*
* @see [https://docs.woocommerce.com/document/template-structure/](https://l.facebook.com/l.php?u=https%3A%2F%2Fdocs.woocommerce.com%2Fdocument%2Ftemplate-structure%2F%3Ffbclid%3DIwAR111uN_g_OxZxizoR4JLgDM56fs1ZkvdH0nLwIFMLgLgmanztvXDCIIAms&h=AT0r5RXVtLMarDLBOxYtIFWFkQ5QkDo8acQgY-Pu8vP1Y-qhXE0ykLzygcdl3clToB89kyljNsMTqGXuSpPRbk_fh-T-J5s-2QNOjCqzkmDZap2I3eTWrTWxcwV2oJwO5swg&__tn__=-UK-R&c[0]=AT0QoNWbbnSyhzCLCJaig7JTrSZfxTY3I_c1nohApvBB_39EH3XLU8Jx3G0pxVEP52LpnVIYtjBVf-uocIyBtDCR1HiLsRS8rJVL0Em3r3kuRyLgtHcbFzO-x-mUBqyXhR-iuvZjLFw-lQVQYP-1kZFNGwEoZ94V)
* @package WooCommerce/Templates
* @version 3.4.0
*/
defined( 'ABSPATH' ) || exit;
get_header( 'shop' );
/**
* Hook: woocommerce_before_main_content.
*
* @hooked woocommerce_output_content_wrapper - 10 (outputs opening divs for the content)
* @hooked woocommerce_breadcrumb - 20
* @hooked WC_Structured_Data::generate_website_data() - 30
*/
do_action( 'woocommerce_before_main_content' );
?>
<header class="woocommerce-products-header">
<?php if ( apply_filters( 'woocommerce_show_page_title', true ) ) : ?>
<h1 class="woocommerce-products-header__title page-title"><?php woocommerce_page_title(); ?></h1>
<?php endif; ?>
<?php
/**
* Hook: woocommerce_archive_description.
*
* @hooked woocommerce_taxonomy_archive_description - 10
* @hooked woocommerce_product_archive_description - 10
*/
do_action( 'woocommerce_archive_description' );
?>
</header>
<?php
if ( woocommerce_product_loop() ) {
/**
* Hook: woocommerce_before_shop_loop.
*
* @hooked woocommerce_output_all_notices - 10
* @hooked woocommerce_result_count - 20
* @hooked woocommerce_catalog_ordering - 30
*/
do_action( 'woocommerce_before_shop_loop' );
if( ! function_exists('wcpt_archive_override') || ! wcpt_archive_override() ){
woocommerce_product_loop_start();
if ( wc_get_loop_prop( 'total' ) ) {
while ( have_posts() ) {
the_post();
/**
* Hook: woocommerce_shop_loop.
*
* @hooked WC_Structured_Data::generate_product_data() - 10
*/
do_action( 'woocommerce_shop_loop' );
wc_get_template_part( 'content', 'product' );
}
}
woocommerce_product_loop_end();
}
/**
* Hook: woocommerce_after_shop_loop.
*
* @hooked woocommerce_pagination - 10
*/
do_action( 'woocommerce_after_shop_loop' );
} else {
/**
* Hook: woocommerce_no_products_found.
*
* @hooked wc_no_products_found - 10
*/
do_action( 'woocommerce_no_products_found' );
}
/**
* Hook: woocommerce_after_main_content.
*
* @hooked woocommerce_output_content_wrapper_end - 10 (outputs closing divs for the content)
*/
do_action( 'woocommerce_after_main_content' );
/**
* Hook: woocommerce_sidebar.
*
* @hooked woocommerce_get_sidebar - 10
*/
do_action( 'woocommerce_sidebar' );
get_footer( 'shop' );

**Comment by tmrwltd** [comment]
Have had a similar problem with the Pro version. In the end, I threw out code snippets on all pages and replaced them with WPCodeBox - and never had problems again.

**Comment by sheabunge** [comment]
This is caused by some faulty code added as a snippet. Activating safe mode allows you to login and deactivate the snippet causing a problem, but you still need to remove the bad code to have your site work again.

If you deleted the snippet but still having issues with the site when Code Snippets is active and not in safe mode, then there's another snippet causing issues that's still active.
