### ISSUE TITLE
Critical Error by uncaught TypeError

### ISSUE THREAD

**Issue by FlorinBuffet** [sheabunge/code-snippets#178]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Code Snippets.

### Type of Bug

Product/Pro 3.5.0-beta.1

### Description

I got critical errors when trying to edit a page with following stacktrace:
`Stack trace:
#0 /var/www/vhosts/buffetitservices.ch/tanjaklein.buffetitservices.ch/wp-content/plugins/code-snippets-pro/php/snippet-ops.php(409): Code_Snippets\update_shared_network_snippets()
#1 /var/www/vhosts/buffetitservices.ch/tanjaklein.buffetitservices.ch/wp-content/plugins/code-snippets-pro/php/class-list-table.php(841): Code_Snippets\activate_snippets()
#2 /var/www/vhosts/buffetitservices.ch/tanjaklein.buffetitservices.ch/wp-content/plugins/code-snippets-pro/php/class-list-table.php(1010): Code_Snippets\List_Table->process_requested_actions()
#3 /var/www/vhosts/buffetitservices.ch/tanjaklein.buffetitservices.ch/wp-content/plugins/code-snippets-pro/php/admin-menus/class-manage-menu.php(153): Code_Snippets\List_Table->prepare_items()
#4 /var/www/vhosts/buffetitservices.ch/tanjaklein.buffetitservices.ch/wp-includes/class-wp-hook.php(308): Code_Snippets\Manage_Menu->load()
#5 /var/www/vhosts/buffetitservices.ch/tanjaklein.buffetitservices.ch/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#6 /var/www/vhosts/buffetitservices.ch/tanjaklein.buffetitservices.ch/wp-includes/plugin.php(517): WP_Hook->do_action()
#7 /var/www/vhosts/buffetitservices.ch/tanjaklein.buffetitservices.ch/wp-admin/admin.php(237): do_action()
#8 {main}
  thrown
`

### Steps to reproduce

Don't really know, sorry....
But it was fixed by rolling back to 3.4.2.2

### Isolating the problem

- [X] This bug happens with only the Code Snippets plugin active (Free or Pro).
- [ ] This bug happens with a Blank WordPress theme active. For example: ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### Comment

```markdown
.
```

**Comment by sheabunge** [comment]
This likely the same issue as https://wordpress.org/support/topic/activating-snippets-breaks-on-wordpress-6-3/.

**Comment by sheabunge** [comment]
I appreciate the report! I'll make sure this fix is included in the next release.
