### ISSUE TITLE
Code Snippets import function not working

### ISSUE THREAD

**Issue by GiraldoMedia** [sheabunge/code-snippets#185]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Code Snippets.

### Type of Bug

Export/Import

### Description

Code snippets import function is not working when I try to import existing code snippets.

### Steps to reproduce

1) import snippets
2) successful import message displayed
3) check all snippets and imported snippets are missing

### Isolating the problem

- [X] This bug happens with only the Code Snippets plugin active (Free or Pro).
- [ ] This bug happens with a Blank WordPress theme active. For example: ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### Comment

```markdown
using version 3.2.1
```

**Comment by sheabunge** [comment]
I'm afraid that I'm not able to reproduce this. Have you tested with various snippet types?

Can you share an export file which isn't working here for us to test with?
