### ISSUE TITLE
Shared Snippets on multisite

### ISSUE THREAD

**Issue by signo** [sheabunge/code-snippets#19]
An enhancement for this plugin would be to add a shared flag field to the edit snippet screen when editing a snippet in the network admin area, then a single site would see it's own snippets plus the shared snippets, this way a network admin could write snippets to be used by all sites in a multisite setup, only network admins would be allowed to edit shared snippets.

**Comment by sheabunge** [comment]
That's a fantastic idea. Thanks for providing it in such detail; it will make it much easier to implement. I'll get onto this as soon as I can.

**Comment by signo** [comment]
I can´t wait for this feature to be implemented. btw you have developed a great and useful plugin.

**Comment by signo** [comment]
Hi, i have noticed that you have been working on this feature and since i am installing a new multisite setup i just wonder, will you have a working beta soon?, no rush, if it is a couple of days i can pause the new installation, if it is more, no problem i test it later.

Cheers!!

**Comment by sheabunge** [comment]
I'm working on it, but it will probably be a few more days before I can get a release ready (I'm a bit busy at the moment), so it's probably better to set up your network now, and then test the new feature when it's ready.

**Comment by sheabunge** [comment]
Added in 2.4.1
