### ISSUE TITLE
URGENT CRITICAL ERROR - A lot of sites are down because the version 3.6.5 add a "q" at start of code-snippets.php and break the site.

### ISSUE THREAD

**Issue by MiniSuperDev** [sheabunge/code-snippets#190]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Code Snippets.

### Type of Bug

Product/Core

### Description

Hello, for some reason in some installations of the version 3.6.5 a `q` is added to that line as you can see in the image.
I don't know if it is a conflict with another plugin or something in the plugin but it happens to many.
It is urgent to fix it since the sites practically go down, the sitemap does not work, etc.

Thank you

https://github.com/codesnippetspro/code-snippets/blob/47b323d3a005914cb09a6e961f47b6f799ef57b6/code-snippets.php#L1
![image](https://github.com/codesnippetspro/code-snippets/assets/105388540/6d91bba7-4ed2-4fda-9f10-db5d77e6e4bf)

Checkout the last reviews
https://co.wordpress.org/plugins/code-snippets/#reviews

![image](https://github.com/codesnippetspro/code-snippets/assets/105388540/887ec791-1c56-4a9d-aabe-ce95e402b642)

### Steps to reproduce

Install the plugin version 3.6.5.

### Isolating the problem

- [ ] This bug happens with only the Code Snippets plugin active (Free or Pro).
- [ ] This bug happens with a Blank WordPress theme active. For example: ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### Comment

```markdown
I'm only use the Free version, I don't know if this bug is in the pro also.
```

**Comment by MiniSuperDev** [comment]
https://plugins.trac.wordpress.org/changeset/3093592/code-snippets/tags/3.6.5/code-snippets.php
I see that you fix it.

But I think you should increase the version at least for 3.6.6 for the sites reflect the changes.

## A temporal solution for anyone is to uninstall the plugin and reinstall it.

**Comment by sheabunge** [comment]
Thanks for reporting this here. It was an issue that occurred during deployment – I've released a new point release with the corrected file.
