### ISSUE TITLE
Can't create new snippet tags

### ISSUE THREAD

**Issue by pauserratgutierrez** [sheabunge/code-snippets#196]
### Current behavior

The tags in the edit snippet page no longer work, in both Free (v3.6.6.1) and Pro (v3.6.6.1) versions of the plugin. I tried, I cannot add tags even though a typing cursor indicator appears

### Expected behavior

Should be able to type a tag.

### Steps to reproduce

Installing the plugin normally, both Free and Pro versions.

### WordPress version

6.7.1

### Code Snippets version

3.6.6.1

### Code Snippets license

Core (free), Pro

### Anything else?

![image](https://github.com/user-attachments/assets/dfc88505-7421-4da7-9141-f4de47c6be92)

**Comment by sheabunge** [comment]
@codesnippetspro/devs this is ready to go out, please review!
