### ISSUE TITLE
Saving an empty snippet does not show a warning on Pro

### ISSUE THREAD

**Issue by sheabunge** [sheabunge/code-snippets#197]
## Current behavior

When saving a snippet using the small 'Save Changes' button above the code editor, if the snippet us missing its name or its code, a dialog box should appear for confirmation.

## Expected behavior

The dialog box works correctly in Core, but not Pro.

## Steps to reproduce

1. Snippets > Add New
2. leave fields unchanged
3. click the small 'Save Changes' button above the code editor.
4. see how snippet saves without triggering dialog box.

## WordPress version

Version 6.7.1

## Code Snippets version

3.6.6.1

## Code Snippets license

Pro

## Anything else?

Originally raised by [Generosus](https://wordpress.org/support/users/generosus/) here: https://wordpress.org/support/topic/two-findings-v3-6-6-1/

**Comment by Generosus** [comment]
Thank you, Shea.

**Friendly reminder:** Please make sure all top buttons are fixed and tested. Meaning, the "**Generated AI"**, "**Save Changes**", and "**Activate**" buttons. ([details](https://prnt.sc/bhMAaBE1Mm5_))

Cheers!

**Comment by sheabunge** [comment]
Should be fixed in the latest development version! Looks like Pro was still using an older version of the save/activate button component, which didn't have the new dialog box logic integrated in.

We'll aim to release it as a patch in the coming week. Thanks again for bringing it to our attention!

**Comment by Generosus** [comment]
Awesome, thank you!  Do you know what the plugin build or revision level will be?

**Comment by sheabunge** [comment]
The commit won't be in this repository, as it's in the Pro build, but the release version should be 3.6.7.
