### ISSUE TITLE
In Settings, move the Theme select down by the Editor Preview

### ISSUE THREAD

**Issue by brandonjp** [sheabunge/code-snippets#206]
### Is your feature request related to a problem? Please describe

Just a minor UX suggestion. Usually a user (myself... often) will want to see what a theme looks like after they've selected it. Sometimes a user forgets which theme they typically use (myself... often) so I... the user has to scroll the page up and down until I see the one I frequently use (Yonce... I think).

![Image](https://github.com/user-attachments/assets/e063e73a-d065-4a7e-8358-13bf97cd6f4f)

### Describe the solution you'd like

In Settings, move the Theme select down the page to sit above the Editor Preview.

![Image](https://github.com/user-attachments/assets/76f7181b-08c3-4915-9456-fcb5690a138e)

**Comment by sheabunge** [comment]
Very good point, and I appreciate the simplicity of the solution. Thank you!
