### ISSUE TITLE
On Import Snippets page, link to 'All Snippets' page is not clickable.

### ISSUE THREAD

**Issue by alanjacobmathew** [sheabunge/code-snippets#209]
### Current behavior

  `Afterward, you will need to visit the All Snippets page to activate the imported snippets.` 

Here the 'All Snippets' link is not clickable. 

![Image](https://github.com/user-attachments/assets/ea6e9de5-cc4e-4bfd-b5d9-d8c680e91e80)

### Expected behavior

The above mentioned link is clickable and takes the user to the manage page.

### Steps to reproduce

Open the Import Snippet page, hover on 'All snippets' text

### WordPress version

6.7.1

### Code Snippets version

3.6.6.1

### Code Snippets license

Core (free)

**Comment by sheabunge** [comment]
Good catch, thank you!
