### ISSUE TITLE
Javascript error

### ISSUE THREAD

**Issue by signo** [sheabunge/code-snippets#22]
Since your last update i am receiving the following javascript error:

`Uncaught TypeError: jQuery(...).resizable is not a function`

This is the link that reports the error:
`http://site.dev/wp-admin/admin.php?page=edit-snippet&id=<script id>`

**Comment by sheabunge** [comment]
Thanks for bringing this to my attention. It looks like this was part of some test code that was accidentally committed. I'll get rid of it.
