### ISSUE TITLE
Grouping sugestion

### ISSUE THREAD

**Issue by signo** [sheabunge/code-snippets#23]
Kudos for the snippet scope enhancement. May i suggest to add an "Admin" and "Front End" grouping to the Manage Snippets screen to easily detect witch snippets are admin only or front end only? The grouping should be:  All (n)  Active (n)  Inactive (n) Admin (n) Front End (n)

**Comment by sheabunge** [comment]
This is a great idea; thanks for the suggestion.

**Comment by signo** [comment]
Sorry to reopen this issue, but could it be possible to add a class to a snippet indicating if it is marked as admin or front end? this enhancement will make it possible to set a background color or add an icon/mark to each snippet indicating it´s execution type.

**Comment by sheabunge** [comment]
This is a great idea; I've added the class, though I think that a background colour might be too in-your-face. Perhaps an icon next to the snippet would be best, I just need to think of what to use.

Also, do you think that it would be a good idea to add a 'global' group filter as well?

**Comment by signo** [comment]
The 'global' state could be useful but not necessary, i would make the decision based in the real state it will occupy in that part of the screen, if you don´t think in the future you will be adding more groups or a field in that part of the screen, sure add it.

**Comment by signo** [comment]
About the icons, you could use Font Awesomes' fa-gauge or fa-cog-alt for the admin snippets and fa-home for the font end snippets, or using Entypo you could use ´window' or 'eye' for front end and ´cog' for admin. In Fontello http://fontello.com/ you can check this icons and a bunch more for you to decide, hope this helps.

**Comment by sheabunge** [comment]
Thanks for the icon suggestions, but I ended up using Dashicons, as it's built into WordPress already and matches the style of the rest of the administration area.

There's one thing that I'm not too sure about though: do you think that I should also add an icon for global snippets? 

![](http://i.imgur.com/tniOpSy.png)

I think that it looks nice like that, but it might seem a bit redundant if someone doesn't use (many) different scopes and just has a whole lot of global snippets.

**Comment by signo** [comment]
The icons look great! Maybe consider the dashicons-welcome-view-site for front end snippets, the eye inside the screen may be more appropriate, but the paintbrush look simpler, in the end i would base the decision on which one looks better. I would leave the global icon out, as you say it would be redundant, and just by having no icon it will stand out.

**Comment by sheabunge** [comment]
I've changed the icons, but I think that having an empty space next to global snippets looks a little strange, so I've moved the icons to the end of the snippet name. I think that this looks much better, even though it means the icons are not lined up. Thoughts?

![](http://i.imgur.com/fm5tL8u.png)

**Comment by signo** [comment]
I think the problem is that the icons are too big. With Photoshop i tried several layouts and the one i like the most is this one
![snippet-icons-3](https://cloud.githubusercontent.com/assets/944774/7666685/be95286c-fbb7-11e4-9329-acfd0294f8f4.jpg)
Placing a small circle by the snippet name you only have the shift the names to the right just a little bit and the circles look very modern, another advantage is that you can make the circles using css, no need to add icons.

What do you think?

**Comment by sheabunge** [comment]
They look quite nice, but I'm worried that they mist be a bit ambiguous as to what the icon refers to.

If you think that the current icons are too large, keep in mind that I can always resize them.

**Comment by signo** [comment]
Ok, i suggest you check if the eye inside the screen looks good at 16 pixels, if it doesn´t you may try the eye icon.

**Comment by sheabunge** [comment]
Well, I've ended up using the eye icon and the cog icon, and sized them so they fit in nicely with the text. Hopefully this works best overall.
