### ISSUE TITLE
Server Error: 501 Not Implemented

### ISSUE THREAD

**Issue by signo** [sheabunge/code-snippets#24]
I just copied a snippet from this page http://www.laplacef.com/how-to-defer-parsing-javascript-in-wordpress/ and i got a 501 server error every time i try to save the snippet, after testing i found that the bellow line causes the problem, it appears that the ! besides the parenthesis is the culprit. I know that line can be simplified but i thought  you would like to know about this issue.

`if (!(is_admin() )) {`

**Comment by sheabunge** [comment]
I can't see any errors in this line or the snippet, and it doesn't produce any when I try it out. I'm not sure how to reproduce it.

You could try moving the `is_admin()` check *inside* the function.

```php
function defer_parsing_of_js ( $url ) {
	if ( is_admin() || FALSE === strpos( $url, '.js' ) ) {
		return $url;
	}
	
	if ( strpos( $url, 'jquery.js' ) ) {
		return $url;
	}
	return "$url' defer onload='";
}
add_filter( 'clean_url', 'defer_parsing_of_js', 11, 1 )
```

**Comment by signo** [comment]
I tried saving a snippet with only this line `if (!(is_admin() )) { }` and i got three different results.

1) On my localhost, xampp, there is no problem.
2) In my main webhosting account from crocweb with litespeed i got the 501 error
3) in a cheap hosting account from wpwebhost with apache i got some weird 404 error, even though the url says wp-admin/admin.php?page=snippet it shows the frontend´s 404 page.

So it looks as if the problem occurs in linux but not in windows, i don´t know about macs since i don´t have one now for testing. Anyways i am just reporting this for you to decide if it can be a problem worth looking into.

**Comment by sheabunge** [comment]
This is interesting. Thanks for reporting it, but there's not much I can do about it if I can't reproduce the error. I only ever really use Linux, for both testing and production, so it's strange that I am not receiving this error, but then again I use nginx as well, so perhaps it's an issue with Apache on Linux. I'll try testing it out.

**Comment by sheabunge** [comment]
Well, I tried creating a new server using [VVV Apache](https://github.com/ericmann/vvv-apache) and creating a snippet with only `if (!(is_admin() )) {}` as the code, but there's still no error. I'm sorry, but I can't seem to reproduce the error at all.
