### ISSUE TITLE
Unlocalizeable strings in class-settings.php

### ISSUE THREAD

**Issue by achumakov** [sheabunge/code-snippets#27]
No strings in the mentioned file are localizeable by .po.
Probably, some bug is there.

**Comment by sheabunge** [comment]
It was indeed a bug. The setting names were being 'translated' before the translation files had been loaded. I've applied a fix in f6d7b1540d3cab34fc0adce865a0b033dfb2748f

Additionally, a few of the settings weren't using the WordPress translation methods, so they still need to be translated in the PO file.

**Comment by sheabunge** [comment]
By the way, thanks for letting me know about this bug
