### ISSUE TITLE
Snippet import Error

### ISSUE THREAD

**Issue by signo** [sheabunge/code-snippets#32]
I just created an export file from the site i have my snippets to import them to a new site, when i click the "Upload file and import button" all i get is a new browser page with the url http://array/, both sites have wp 4.2.2 and the latest code-snippets version installed. I deactivated all the plugins but code-snippet before the import to discard any conflict. I tried importing a snippet file that i exported with the previous version and still the same problem.

**Comment by sheabunge** [comment]
Thanks very much for reporting this bug. It looks like it was accidentally added in ab191c795eb8b78d1d13c1d9e71f82273ed675f2. The fix should be included in version 2.3.0, which will hopefully be coming out very soon.

However, to me it appears that this bug only takes place *after* importing, when the results are displayed to you. So the snippets should still have been imported regardless of this error, right?

**Comment by signo** [comment]
Yes, it did import the snippets with no problem. One observation though, i did import the file several times testing, this of course made several repeated copies of the snippets, i know there is no way to make an unique id for snippets, but maybe you could check the snippet name to avoid repetitions, or better yet you could place a radio button in the import screen with options to "replace existing snippets" or ignore "existing snippets" this way you can give the user some control on that respect.

**Comment by sheabunge** [comment]
@signo good idea, I've created a new issue with your suggestion so it can be implemented into a future version.
