### ISSUE TITLE
Display snippet code on front-end

### ISSUE THREAD

**Issue by sheabunge** [sheabunge/code-snippets#38]
> See: https://wordpress.org/support/topic/display-snippet-on-front-end

Implement a short code to display a snippet on the front end.

    [code_snippet id="44"]

Possibly also a TinyMCE button to browse the available snippets and insert the shortcode.

**Comment by dnavarrojr** [comment]
+1

**Comment by sheabunge** [comment]
I'm closing this as it's a duplicate of #41, which has been implemented.
