### ISSUE TITLE
Saving/Editing Enhancements

### ISSUE THREAD

**Issue by dnavarrojr** [sheabunge/code-snippets#39]
I would love an option in settings to disable the full-height editor.  And disable the description and tags fields (I don't use them).

I'd also love it if you used Ajax to save and put a SAVE button above the editor.  That way the page doesn't reload each time I save.

**Comment by sheabunge** [comment]
I'll include new settings for disabling the tags and description editors (along with their columns in the manage table).

I'll need to look into implementing Ajax in a future version, but it sounds like a great idea.

In regards to the second save button, do you think it should be the full row of buttons (Save and Activate, Save, Edit, Delete), or just Save and Save and Activate, or simply a 'Save' button? What would your preference be?

I am a bit hesitant to add a second button though, as it goes against the other WordPress admin menus, and I'm not sure it would work great in the page.

**Comment by sheabunge** [comment]
-
