### ISSUE TITLE
Use Plugin as Library?

### ISSUE THREAD

**Issue by marbetschar** [sheabunge/code-snippets#41]
I really love this plugin - thank you very much for your excellent work!!!

As I have lots of code snippets flying around, and would also like to publish some of them, is it possible to use a shortcode for rendering code as text in a blog entry?

And additionally it would be great to store snippets from multiple languages - these shouldn't be executed of course, but this way I can save all of my snippets in one convenient place. I know this may be out of scope of the plugin, but it would be awesome!! Maybe just adding a language dropdown menu just before the code editor is enough - and if the language is not PHP, then it's not possible to activate the snippet at all.

**Comment by sheabunge** [comment]
These are both great ideas, thank you for suggesting them. It would take a bit of reworking the plugin, but I'd really like to see these implemented, as I think it will open the scope of the plugin up a lot and make it more useful.

**Comment by marbetschar** [comment]
Very cool!! I've already played around with it a bit and added a shortcode, which renders itself on the frontend: http://marco.betschart.name/code-snippet/

Also I'm currently playing with Crayon - the syntax highlighting should already work, but for some reason it doesn't. Maybe Crayon kicks in earlier?

The idea is to have a language dropdown in the admin and pass it's value to crayon by outputting simply the following code:

    <pre class="lang:php-or-whatever">...</pre>

**Comment by marbetschar** [comment]
@sheabunge 
Despite Christmas and the new year parties coming along these days; Do you have any plans when these changes will be available?

**Comment by sheabunge** [comment]
I've added the snippet code shortcode in version 2.6.0. I have also integrated the [PrismJS](http://prismjs.com) library for basic syntax highlighting - it will only load on pages using the shortcode, and can be disabled on the plugin settings page.

Here is the syntax for the shortcode:

```
[code_snippet id=42]
[code_snippet id=11 network=true]
```

I'm hoping to add a visual editor button where you can browse available snippets and just click on one to insert it in a future version.

**Comment by sheabunge** [comment]
Also, since the multiple languages idea is already mentioned in #28 and #42, I'll close this issue for now.

**Comment by marbetschar** [comment]
Very cool to see this feature in the official release, thank you very much!!

Just two things:
- The snippet shortcode is wrong in the changelog here: https://de.wordpress.org/plugins/code-snippets/changelog/
- For some reason, the syntaxhighlighting is not working in my blog: http://marco.betschart.name/code/ - any suggestions? It's enabled in the settings :(

**Comment by sheabunge** [comment]
1. Thanks, I'll update the changelog for the next release

2. Can you link to an actual post on your blog which is using the shortcode?

Sorry for the extremely late response; I've been on holiday for most of January and I'm still in the middle of sorting things out.
