### ISSUE TITLE
Add bulk option for marking a snippet as shared network

### ISSUE THREAD

**Issue by sheabunge** [sheabunge/code-snippets#43]
Instead of needing to individually edit a snippet to mark it as shared across a multisite network, there should be a bulk option for this on the manage snippets page.

**Comment by Ver3** [comment]
Now that you mentions this... it would be awesome if you can activate snippets on all site you've installed the plugin and are loggen in with your 'Code Snippets Account'.

Not sure if a service like this is possible, put I would pay for it. Especially if CSS is also supported.

Just my two cents though.

**Comment by sheabunge** [comment]
I'm closing this for now; I'm not sure if it's a necessary or beneficial feature.
