### ISSUE TITLE
There's a Needle in my Error Log

### ISSUE THREAD

**Issue by BurlesonBrad** [sheabunge/code-snippets#46]
I found this in my error_log, but..............
```PHP Warning:  strpos(): Empty needle in /home/pressily/public_html/wp-content/plugins/code-snippets/php/snippet-ops.php(383) : eval()'d code on line 8```
![code-snippet-error-log-github](https://cloud.githubusercontent.com/assets/6208757/17344712/d11349be-58c8-11e6-8eed-df3a9e4f7f21.png)
...............I'm not seeing what the problem might be. Don't get me wrong, it could totally be something _"else"_ in my stack here, but after a bit of _php Googling_, I'm still not able to diagnose if this is really a 'bug' worthy of Git, or something that ought to go over on .org/

Any ideas what could be throwing this error?

**Comment by sheabunge** [comment]
Yep, this is definitely an error in the code of one of your snippets - you can tell from the `eval()'d code` part of the error message. Unfortunately, this message doesn't point to exactly which snippet is triggering the error, so the best way would be to go through your active snippets and test which ones might be causing the issue.

**Comment by BurlesonBrad** [comment]
word.
Thanks!
#AlwaysBeLearning

**Comment by sheabunge** [comment]
No problem, good luck resolving the error!
