### ISSUE TITLE
Treat the snippets as code that can be included and not run

### ISSUE THREAD

**Issue by lordspace** [sheabunge/code-snippets#51]
I prefer to enter a piece of code as is and build php code as a plugin.
your plugin should assume it's a plain snippet.
There could be a flag to mark it as runnable code.

**Comment by sheabunge** [comment]
This could be a good idea for something to introduce in a future version.

Just clarifying, is this 'non-runnable' code you are referring to still PHP code, or is it more HTML code or some other language?

**Comment by sheabunge** [comment]
I'm not really certain whether the snippets you are referring to are HTML snippets intended to be output directly on the page (in a shortcode), or pure PHP snippets that include functions and methods which are then used elsewhere on the site.

Either way, the first is addressed in #28, and the second in #53 and #18.
