### ISSUE TITLE
Editor indents and hides code behind line numbering column

### ISSUE THREAD

**Issue by samkatakouzinos** [sheabunge/code-snippets#52]
When I edit code I cannot see ~4-6 characters on the left hand side. 
The line numbering column seems to hide it. 

Wordpress 4.7 Multisite Subdomain

**Comment by samkatakouzinos** [comment]
Here is a screenshot: http://i.imgur.com/Az9z7Oc.png

The full text in the code window is;
`add_filter('autoptimize_filter_css_fonts_cdn',__return_true);`
The first ~4-6 characters seem hidden on the left hand side. 

> And are you using the default editor theme, or a custom one? 
May you clarify this question?

**Comment by sheabunge** [comment]
This looks like it may be due to a conflict with a different plugin that is loading a different version of CodeMirror on this page. What plugins do you have installed that may be doing this? (Debug Bar Console is a known one.)

**Comment by samkatakouzinos** [comment]
Child Theme Configurator
Network Active
When using the Customizer is not enough - Create child themes and customize styles, templates, functions and more.
Version 2.2.4.1 | By Lilaea Media | View details

Code Snippets
Snippets | Network Active
An easy, clean and simple way to add code snippets to your site. No need to edit to your theme's functions.php file again!
Version 2.8.0 | By Shea Bunge | View details | About | Support | Donate

Debug Bar
Network Active
Adds a debug menu to the admin bar that shows query, cache, and other helpful debugging information.
Version 0.8.4 | By wordpressdotorg | View details

Debug Bar Console
Network Active
Adds a PHP/SQL console to the debug bar. Requires the debug bar plugin.
Version 0.3 | By koopersmith | View details

Disable Emojis
Network Active
Disable Emojis
Version 1.5.3 | By Ryan Hellyer | View details

Nginx Helper
Network Active
Cleans nginx's fastcgi/proxy cache or redis-cache whenever a post is edited/published. Also does a few more things.
Version 1.9.9 | By rtCamp | View details

Query Monitor
Network Active
Monitoring of database queries, hooks, conditionals and more.
Version 2.13.2 | By John Blackbourn | View details

Redis Object Cache
Network Active
A persistent object cache backend powered by Redis. Supports Predis, PhpRedis, HHVM, replication, clustering and WP-CLI.
Version 1.3.5 | By Till Krüss | View details

**Comment by sheabunge** [comment]
Try deactivating the Debug Bar Console plugin and see if that fixes things.

**Comment by samkatakouzinos** [comment]
> Try deactivating the Debug Bar Console plugin and see if that fixes things. 

Done, screenshot: http://i.imgur.com/bOaARpD.png 
It looks much better.

**Comment by sheabunge** [comment]
Unfortunately, Debug Bar Console uses a very outdated version of CodeMirror which it loads on every page. A workaround I used in the past was unloading the Debug Bar CodeMirror on this page, but it's a bit hacky and it looks like it must have broken at some point. I'll see what I can do about fixing this.

**Comment by sheabunge** [comment]
This will be fixed in version 1.8.1.
