### ISSUE TITLE
HTML permitted in snippet title

### ISSUE THREAD

**Issue by atdr** [sheabunge/code-snippets#55]
Bug? I would have expected the title to be [sanitised](https://codex.wordpress.org/Validating_Sanitizing_and_Escaping_User_Data#Sanitizing:_Cleaning_User_Input). Example below.

![adding the snippet](http://i.imgur.com/HG07vBS.png)

![snippet list view](http://i.imgur.com/Kl0eTpU.png)

**Comment by sheabunge** [comment]
I think this was expected behaviour - I trying to follow how post titles work, and I believe they allow HTML on the front-end.

I agree that this should probably be changed though, so I'll add some sort of sanitisation, or at the very least escaping HTML on output.

**Comment by sheabunge** [comment]
I've updated this in the master branch; it will be part of the next release. Thanks!
