### ISSUE TITLE
Indonesian translation

### ISSUE THREAD

**Issue by zmni** [sheabunge/code-snippets#56]
Sorry for previous translator but everything is wrong with that translation.

So I redo them all and upload them on Code Snippets's [WordPress.org localization page](https://translate.wordpress.org/projects/wp-plugins/code-snippets/dev/id/default) (development trunk). I'm not familiar with git, maybe @sheabunge can help merge them.

Thanks for the plugin btw, it's super usefull.

**Comment by sheabunge** [comment]
Thank you for correcting the translations! I did think there was something a little off with the contributed translations, but I included them anyway after a bit of fixing up of the formatting.

Unfortunately, WordPress.org translations work on a competely different system than I am used to. I am still getting used to it, but I believe we now need to wait until a Translation Edtior for Indonesian comes along and approves the translations, and then they will be automatically downloaded into WordPress installations which need them. 

Until then, it doesn't look like I will be able to grab a .po file and include the new translations in the plugin to update the old ones. My apologies. I will keep looking around and seeing if there is some way of getting the new translations in .po format.

**Comment by zmni** [comment]
I see. In that case, it will get really long time to get approved. They (id_ID translation team) only focus on the core and maybe some of the most popular plugins.

So, I generate new .po and .mo ([code-snippets-id_ID.zip](https://github.com/sheabunge/code-snippets/files/999354/code-snippets-id_ID.zip)) from your latest .pot file commit: af944af . Maybe this can be use. If not, well, we'll just wait and see.

You can close this issue if you like. Thanks.

**Comment by sheabunge** [comment]
Thank you very much; that is extremely helpful.

I'll add the new translations to the plugin, and they will be included in the next release.

Would you like me to add your name/website credit to the readme and changelog?

**Comment by zmni** [comment]
No. This plugin it self is enough for me, help me save a lot of times. Thank you.

**Comment by sheabunge** [comment]
Well, thank you very much for your help :) 

If you change your mind, it wouldn't be any trouble to add something in the translations section of the readme. Thank you!
