### ISSUE TITLE
Connexion reset while saving with echo "<script>"

### ISSUE THREAD

**Issue by nathan30** [sheabunge/code-snippets#59]
Hi,

I'm facing an issue really annoying. I have to put some code line like this : 

  `echo '<script type="text/javascript" src="'.site_url().'/edissyum/script.js"></script>';`

But everytime there is a line like this, I have this error (on Firefox). Without those type of code, mixing echo and <script>, the snippet is saved.

Any idea ? 

We have already check the firewall, we have the whole rights, Apache doesn't throw an error (under Debian 8).

**Comment by sheabunge** [comment]
It's hard to say, as I am unable to reproduce this error. Of course, a workaround could be to use something like `printf()`, but I realise that doesn't address the actual issue.

If I can work out how to reproduce this, then I could get onto the path to fixing it, but unfortunately until I can there isn't a whole lot I can do.

**Comment by nathan30** [comment]
Hi. Little update, the snippet insn't the cause. There is some security rules on the server, disabling them solve my problem. 

BTW, thanks for your answer :)

**Comment by sheabunge** [comment]
It's great to hear that you managed to sort out this issue! Would you mind sharing which rules were causing the issue? It would be helpful for me to know how to advise the next person to report something like this.

**Comment by nathan30** [comment]
I would love to, but this is on a customer server, so I didn't know whats rules was problematic :/ But I think this prevent JS intrusion, this is all I can tell about this, sorry :/ But keep up the good work with Code Snippet, really usefull plugin :)
