### ISSUE TITLE
Move Settings Above the Fold

### ISSUE THREAD

**Issue by heyjoecampbell** [sheabunge/code-snippets#62]
Move Settings (Scope) under title

Also, you could abbreviate: 
Everywhere  |  Back-end Only  |  Front-end Only

**Comment by sheabunge** [comment]
This is an interesting idea. Do you think that simplifying the settings like this would perhaps make them more difficult to understand for new users?

**Comment by heyjoecampbell** [comment]
Good point abbreviating the text could potentially make it harder to understand for WordPress newbies, but moving it under the title is still a good idea. 

In fact, removing the "Settings" and "Scope" titles would also make it look cleaner.
http://i.imgur.com/CmzQ47r.png

**Comment by sheabunge** [comment]
I have done as you suggested in version 2.9.6. Thanks!
