### ISSUE TITLE
Bulk Import Feature

### ISSUE THREAD

**Issue by lukecav** [sheabunge/code-snippets#65]
Having a feature of being able to bulk import multiple code snippets would be very useful.

**Comment by sheabunge** [comment]
I'm fairly certain this feature already exists, through the Tools > Import > Code Snippets admin menu.

Is there something missing from this process that should be added?

**Comment by lukecav** [comment]
That is to import on snippet at a time, I mean a way to import multiple snippets in one go.

**Comment by sheabunge** [comment]
If you have an import file containing multiple snippets, then this page will import all of the snippets in that file.

Are you thinking of adding a feature where you can upload multiple files at a time?

**Comment by lukecav** [comment]
Yep correct for a feature so you can upload multiple files at once.

**Comment by sheabunge** [comment]
Should be doable; I'll see what I can do

**Comment by sheabunge** [comment]
Feature implemented; it'll be included in the next plugin release.
