### ISSUE TITLE
v 2.11.0 Save and \n bug(s)

### ISSUE THREAD

**Issue by patdaman** [sheabunge/code-snippets#70]
** 2018-07-24 -- v.2.11.0**

I do not have time for a full bug review, but there is an issue with today's release.

- Saving a snippet will cause the page to enter an infinite loop.
- Pressing carriage return, the code below the cursor gets completely deleted.  
  - I have only noticed this with the "Enter" button on my QWERTY keyboard, but the number pad "Enter" doesn't seem to exhibit this behavior.
  - This change is not saved automatically, but it does require a refresh and during that time I hope that no one attempts to save!

Thanks for an otherwise awesome product!
_Patrick

**Comment by patdaman** [comment]
I'm sorry that it took so long to reply.  I typed up a response, but somehow didn't post it.
Anywho, the release was pulled back the next morning (Jul 25), but by then I had reversed the update.  When 2.11.1 came out I installed that version, and have not seen the issue ever again.
Thanks!

**Comment by sheabunge** [comment]
It's great to hear that things seem to be working – thank you for the update!
