### ISSUE TITLE
[Feature Request] Server/Client version

### ISSUE THREAD

**Issue by Ver3** [sheabunge/code-snippets#71]
The Client version of the plugin simply connects to one server version securely.

The Server version has all the Code (and maybe even CSS) Snippets. From here you see all connected sites (that have client versions installed). It enables you to remotely inject code/css-snippets from one central location.

This enables many use cases, especially for all companies that build and maintain sites for their clients.  From injecting new ads to fixes for problems. It's an agency's dream.

Please let me know if you need me to elaborate.

**Comment by sheabunge** [comment]
This is certainly an interesting idea.

Would the server version simply be like the current version of the plugin, but with additional capabilities to connect to different sites, or are you envisioning a separate product?

One of the bigger concerns that stands out to me is the question of security. Receiving code from a remote source and executing it is something that could quite easily turn very dangerous, so I feel that there would need to be an extremely robust system of creating secure connections in place before considering something like this.

Like I said, definitely an interesting idea – probably not at the top of my to-implement list at the moment, but it does sound like it would be quite useful.

**Comment by Ver3** [comment]
@sheabunge Closing this one. It can still be view by label and will be processed in our progress board.
