### ISSUE TITLE
Parse error that could not allow me to delete added html file

### ISSUE THREAD

**Issue by Hazloe** [sheabunge/code-snippets#72]
Am not coder at all, but teaching myself how to do things by myself.

So when i came across the **code snippet** plugin, i loved it.

Today i added a google console html file and received the following message to my website:

**Parse error: syntax error, unexpected ':' in /home/thextra1/public_html/wp-content/plugins/code-snippets1/php/snippet-ops.php(352) : eval()'d code on line 1**

But the host at siteground disabled the plugin and gave me the following message:

_<<Yes, unfortunately it seems that something is misconfigured with the plugin. What I suggest is indeed to reach out to the dev team of the plugin on the matter, and perhaps request a stable version that you can download from their end. They can also check on the current issue you are facing with it, and advice you further>>_

**Comment by sheabunge** [comment]
Glad to hear that you're enjoying the plugin :) 

The error message you are receiving actually comes some code that you have added as a snippet, and not from the plugin itself. There's not a lot that I can do for the plugin itself – this is something that you'll need to fix on your site.

It's possible that the code you're using isn't written properly to work with WordPress or PHP snippets, and might need some tweaking. If you'd like to post it here, I can give you some tips on how to fix it up.
