### ISSUE TITLE
The wp_snippets table gets associated with other plugins.

### ISSUE THREAD

**Issue by Norm6257** [sheabunge/code-snippets#79]
Hi... I'm not sure of how plugin tables get "owned" by a plugin, but I have seen the wp_snippets table get "owned" by another plugin.  I have seen Beaver Builder and Auto Optimize own the table.  This has definitely caused problems on a couple of sites for me. See this image:  [https://cl.ly/aee199356850]

I get the table ownership report by running Plugins Garbage Collector [https://wordpress.org/plugins/plugins-garbage-collector/]

It seems like maybe code-snippets is not properly claiming ownership association of the table?

**Comment by sheabunge** [comment]
Thanks for reporting this. I'm not too clear on what table ownership entails either – it might be a term invented by the Garbage Collector plugin – but I'll take a look at the plugins you mention and see if I can figure out what's causing this.

I am wondering, though: what are the "problems" caused by this false analysis? Does it have an impact on functionality of Code Snippets or another plugin?

**Comment by sheabunge** [comment]
I have taken a good look at the Garbage Collector plugin, and it looks like the system used for determining which tables are owned by which plugins is very rudimentary. It essentially scans all the .php files in each plugin, finding if any unprefixed table names are used in any context, and adding them to the list.

What this means is that any plugin that even mentions the word "snippets" anywhere in its .php files will be counted as owning the `snippets` table. If you run the Garbage Collector plugin on a multisite network, you can see how the `ms_snippets` table is only ever shown as being owned by this plugin as it is more of a unique name unlikely to appear in any other context.

**Comment by Norm6257** [comment]
Interesting... so the 'ownership' really isn't true ownership, just a probability.  Although I do find that it seems to work for most plugins.  Anyway, that would explain why if I delete one of the 'owning' plugins, a new one shows up in place.  Not sure if there is any way to improve on that so that Code Snippets actually shows up as the owner.

As far as impact.... It may be that there is another issue going on.  I had a site that was showing a dismal 2 for Google page insights.  And one plugin specifically was showing issues... BeaverBuilder.  When I looked at Garbage collector it showed BB as the owner for Snippets so I went through a process of deleting snippets.  The Insights score increased to 40.

Snippets had about 7 entries, but none of them were active.  I assumed that if the snippets were all inactive that there would be no performance impact by the snippets and therefore assumed (maybe wrongly) that the invalid 'ownership' of the wp_snippets table was the culprit.  But based on what you found out it is likely that there is something else affecting the performance.

If Snippets are all marked as inactive should there be any performance impact?

**Comment by sheabunge** [comment]
There will actually be some performance impact if all snippets are marked inactive. The plugin will still need to query the database to check whether there are any active snippets to run.
