### ISSUE TITLE
Unable to make changes to existing snippets

### ISSUE THREAD

**Issue by danescobar** [sheabunge/code-snippets#80]
Hi, first of all I want to thank you for your work with code-snippets. One of the most useful plugins available.

The issue I'm having happened after the latest update. Now when I edit an existing active snippet and click save the admin page redirects to a "Non-Existing Page" notice. Like if I'd introduced an invalid address.

The browser's console doesn't report any JS error and the link in the address bar seems correct.
`/wp-admin/admin.php?page=edit-snippet&id=16`

Despite that, instead of the snippet editor only a "Page not found" error default page is shown and I'm out of the admin area.

**Comment by xeydod** [comment]
I am facing the same problem

**Comment by Ver3** [comment]
@danescobar @xeydod Have you tried the latest version and are you still experiencing the problem after the update?

**Comment by Ver3** [comment]
@danescobar @xeydod I'll consider the issue closed for now. If you're still experiencing problems, please let me know.
