### ISSUE TITLE
Crashing my site

### ISSUE THREAD

**Issue by jvpent** [sheabunge/code-snippets#81]
My host, WP Engine, recently updated the PHP for one of my sites to 7.2. When they did, this plugin crashed the site. What are my options?

**Comment by Ver3** [comment]
@jvpent A new version just came out, have you tried it yet?

**Comment by jvpent** [comment]
Just updated to check it out. Can you tell me how to activate in "safe
mode" where my snippets won't be active at first? Is that possible? Thanks,
JP

**Comment by sheabunge** [comment]
Hi @jvpent,

There are two ways to enable safe mode.

The first is to enable the `CODE_SNIPPETS_SAFE_MODE` constant by adding this line to `wp-config.php`, before the `That's all folks` line:

```php
define( 'CODE_SNIPPETS_SAFE_MODE', true );
```


The alternative way is to append `&snippets-safe-mode=1` to the current page URL. So, to view the snippets admin page, the URL would look something like this:

```
https://example.com/wp-admin/admin.php?page=snippets&snippets-safe-mode=1
```

**Comment by Ver3** [comment]
@jvpent I'll consider this one closed. If you still have questions, please let me know.
