### ISSUE TITLE
WP 5.1 + PHP 7.3

### ISSUE THREAD

**Issue by ogoldschmidt** [sheabunge/code-snippets#82]
Since my site runs under WP 5.1 (FR) and PHP 7.3.1 backoffice fails to open pages and posts referencing code snippet because of <? and ?> in the text area

**Comment by sheabunge** [comment]
I'm not really sure what you are saying. Can you elaborate a little further?

**Comment by ogoldschmidt** [comment]
I'm very sorry, it's a mistake ! My problem concern an other plugin (php_everywhere)  used in relation with code_snippet)
