### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by Maverick1983** [sheabunge/code-snippets#83]
I activate my plugin and my site crash with error 500. I can't see server log, because I have only hosting

**Comment by sheabunge** [comment]
Did you use the version downloaded from WordPress.org? And did you add a snippet before it crashed, or did the site crash immediately after clicking 'Activate'?

**Comment by Maverick1983** [comment]
I use version downloaded from WordPress.org.
The site crash immediately after clicking 'Activate'

**Comment by sheabunge** [comment]
Unfortunately, this sort of thing is difficult to diagnose without an error. Are you able to enable `WP_DEBUG` on your server?

**Comment by Maverick1983** [comment]
It's ok. Theme Bug.

Il giorno ven 15 mar 2019 alle ore 13:59 Shea Bunge <
notifications@github.com> ha scritto:

**Comment by sheabunge** [comment]
Ah, right. I'll close this then.
