### ISSUE TITLE
"Finding snippets" wiki page has many bad links

### ISSUE THREAD

**Issue by derelk** [sheabunge/code-snippets#84]
There are many bad links on the [Finding snippets](https://github.com/sheabunge/code-snippets/wiki/Finding-snippets) page. They're either dead or go to isitwp.com which doesn't have any obvious links to any snippets. The first link in "Also see" is mangled as well.

**Comment by sheabunge** [comment]
Thanks for raising this. It's definitely something which needs to be updated.

I'll make sure I redo it in a future version.

Feel free to suggest any replacement resources!

**Comment by VerdiH** [comment]
@sheabunge Please remove the current link and point to our soon to be launched website.
