### ISSUE TITLE
"admin_head" hook doesn't work

### ISSUE THREAD

**Issue by 360fun** [sheabunge/code-snippets#85]
if I create a simple snippet to add JS in the admin area, it doesn't work:
```
function my_custom_admin_head() {
	echo '<script type="text/javascript">console.log(\'admin script\')</script>';
}
add_action( 'admin_head', 'my_custom_admin_head' );
```

if I use the same code in "functions.php" it works...

**Comment by 360fun** [comment]
I found out these icons are actually the scope of the code 😝 
![image](https://user-images.githubusercontent.com/844090/63524179-da4fa980-c4fb-11e9-8ae3-d745103ad9cb.png)

Could you please add a label to make them more clear?
Thanks! 🌳

**Comment by sheabunge** [comment]
Hi @360fun,

Have you tried zooming out a little bit? They should actually have labels next to them.

Here's a screenshot from my site:

![screenshot of snippet scopes](https://user-images.githubusercontent.com/1170783/63530745-6f798f00-c54a-11e9-8ad2-a195289e501f.png)

**Comment by 360fun** [comment]
nope, I had also an issue with the feedback alert: I had to inspect and add text to the link in order to click and close it because all I could see was an empty square. 

this is the code: no text!
![image](https://user-images.githubusercontent.com/844090/63535191-2c4efa00-c511-11e9-819b-0aa99f6e61ec.png)

maybe some strings are missing in the Italian translation...

**Comment by 360fun** [comment]
switching to "English" labels appear: definitely a problem with the localization! ;)
![image](https://user-images.githubusercontent.com/844090/63888172-a504f900-c9de-11e9-89a1-8a21559379a4.png)

**Comment by 360fun** [comment]
fixed?

**Comment by sheabunge** [comment]
Unfortunately, I don't think this is something I can fix, as I cannot translate to Italian.

**Comment by 360fun** [comment]
I can :)

https://github.com/sheabunge/code-snippets/compare/develop...360fun:patch-1

**Comment by sheabunge** [comment]
Looks great! Thank you.
