### ISSUE TITLE
Tweak get_snippets() function to optionally fetch only active snippets

### ISSUE THREAD

**Issue by deckerweb** [sheabunge/code-snippets#86]
Hi,
at first thanks for your wonderful plugin - I've been using it since the beginning and it is indispensable!

My request is that:
Can the function get_snippets() be tweaked in that way, that it would become possible to fetch only snippets that are currently been set active? I can imagine setting another param to the function to achieve this?

This would help me especially for my upcoming improved integration with my Toolbar Extras plugin (which already supports "Code Snippets" btw).

If this is already possible and I just overlooked it, could you please point me in the right direction? Thanks in advance!

Additionally there would be an extended request, to only fetch a certain number of snippets, like, let's say only 10 -- for example: get the latest 10 active snippets. Something like that.

Reasoning behind the request:
- IMO makes more sense to have those kind of helper functions in the Core plugin itself
- I would be more comfortable to have a helper function, filter whatever provided than to bother with database queries myself...

Thanks a lot for any help or tips!

**Comment by VerdiH** [comment]
Hi David, so sorry for the late reply. We've been busy with the upcoming pro version (you're on the beta vip list), the site and other stuff. @sheabunge Could you please answer our friend David?

**Comment by sheabunge** [comment]
My apologies for taking so long to address this @deckerweb!

I've added a third parameter to the `get_snippets()` function which accepts an array of arguments. 

You can specify `[ 'active_only' => true ]` to have the function only return active snippets.

You can specify a maximum number of snippets to retrieve like so: `[ 'limit' => 10 ]`

You can specify a modified ordering of retrieved snippets, like `['orderby' => 'priority', 'order' => 'asc']`.

Hopefully this is what you're looking for! I'll think about other options that might be useful and relatively easy to add. In version 3.0.0 I might do away with the first two parameters to the function and just have the arguments array as a single parameter.
