### ISSUE TITLE
Organize snippets by folders 

### ISSUE THREAD

**Issue by ivodolenc** [sheabunge/code-snippets#87]
Hey, thanks for this awesome plugin! 👍

It would be great if you could add a feature to organize snippets by folders (even better, folder / sub-folder / snippet.php).

For example, in the dashboard plugin, you can add another button "Add New Folder" (next to exist buttons "Add New" and "Import") or something similar. I think this would be a huge win for UX (much better sorting and organizing snippets).

**Comment by sheabunge** [comment]
Thanks for the suggestion!

How would folders be different than organising by tags, like you can now?

**Comment by ivodolenc** [comment]
Thanks for fast reply. 

It's true that I can assign tags to snippets, and this is very helpful, but I think it will be more natural way, if I can first see folders, and inside folder all snippets specific for that main folder.  

Because now I have a lots of snippets and they are all in the plugin main dashboard. Sometimes this is very unorganized if I have enabled option "Show all tags". 

Here is an example, I have 10 snippets related to wordpress dashboard and currently I have assigned them tag "wp-dashboard". They are mixed with many others snippets who don't have the same tag. To be able to view only "wp-dashboard" snippets, I must go to filter and chose "wp-dashboard". And so on for the rest of snippets (other categories).

Without folders:

Plugin root
|- snippet-plugins-1.php
|- snippet-dashboard-2.php
|- snippet-settings-1.php
|- snippet-dashboard-1.php
|- snippet-plugins-2.php
|- snippet-settings-2.php
etc.


> How would folders be different than organising by tags, like you can now?

But if I could add folders to plugin main dashboard, I think it would be more organized, just like browsing folders/files. 

With folders:

Plugin root
|- Admin dashboard (folder)
|-- snippet-dashboard-1.php
|-- snippet-dashboard-2.php
|- Plugins (folder)
|-- snippet-plugins-1.php
|-- snippet-plugins-2.php
|- WP-settings (folder)
|-- snippet-settings-1.php
|-- snippet-settings-2.php
etc.

Don't get me wrong, this is only my opinion/suggestion for possible feature. If you want, you can close this topic.

**Comment by sheabunge** [comment]
We definitely appreciate the suggestion @ivodolenc, especially with the detailed descriptions. We'll consider how we might potentially be able to bring this sort of functionality into a future release.
