### ISSUE TITLE
Add documents for specific situations

### ISSUE THREAD

**Issue by realstephenzhao** [sheabunge/code-snippets#88]
There are no documents and wiki to help beginners, such as activate code snippets on specific pages, custom post types, head, footer, common functions...

I know we may find some documents on codex.wordpress.org, but we are not developers. So there may not be a good result though we had taken a lot of effort.

Please consider adding a help wiki, thanks.

**Comment by VerdiH** [comment]
@realstephenzhao I completely missed your suggestion, sorry. Good news though, as we progress with our upcoming Pro version a Wiki will start to take shape as well. Please wait a little longer. Open a new ticket if you need to know something specific or better yet, join our facebook group: https://www.facebook.com/codesnippetspro/?modal=admin_todo_tour
