### ISSUE TITLE
Where can i find the code of an specific Snippet outside mi WP Admin ? Is it in the database ?

### ISSUE THREAD

**Issue by heysoypaez** [sheabunge/code-snippets#89]
Where can i find the code of an specific Snippet outside mi WP Admin ? Is it in the database ?

**Comment by VerdiH** [comment]
Hey @heysoypaez I'm not sure what you mean but it seems like more of a content question than a technical issue. Maybe our community is better suited to ask your question: https://www.facebook.com/codesnippetspro
