### ISSUE TITLE
Example JavaScript snippet

### ISSUE THREAD

**Issue by judy5** [sheabunge/code-snippets#90]
I by mistake delete the example code in the "Example JavaScript snippet" can I please have the code again so I can place it in the Example so I can know how to use it. Thanks

**Comment by VerdiH** [comment]
Hi Judy. Simply re-install the plugin to get those quickly and without fear of tampering.

**Comment by judy5** [comment]
I did and it did not work.......

---

-------------------------

Regards
 Judy

 0834450940 
admin@happywebi.co.za 
http://www.happywebi.co.za/ 

On 2020-01-16 17:55, Verdi wrote:

> Hi Judy. Simply re-install the plugin to get those quickly and without fear of tampering. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2]. [ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/sheabunge/code-snippets/issues/90?email_source=notifications\u0026email_token=AOJNKSCQXKF3IIBDX4Q5O2LQ6B7PRA5CNFSM4KHQDJIKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEJER5JQ#issuecomment-575217318", "url": "https://github.com/sheabunge/code-snippets/issues/90?email_source=notifications\u0026email_token=AOJNKSCQXKF3IIBDX4Q5O2LQ6B7PRA5CNFSM4KHQDJIKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEJER5JQ#issuecomment-575217318", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]
 

Links:
------
[1]
https://github.com/sheabunge/code-snippets/issues/90?email_source=notifications&amp;email_token=AOJNKSCQXKF3IIBDX4Q5O2LQ6B7PRA5CNFSM4KHQDJIKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEJER5JQ#issuecomment-575217318
[2]

**Comment by judy5** [comment]
it does did after re-install 

---

-------------------------

Regards
 Judy

 0834450940 
admin@happywebi.co.za 
http://www.happywebi.co.za/ 

On 2020-01-16 17:55, Verdi wrote:

> Hi Judy. Simply re-install the plugin to get those quickly and without fear of tampering. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2]. [ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/sheabunge/code-snippets/issues/90?email_source=notifications\u0026email_token=AOJNKSCQXKF3IIBDX4Q5O2LQ6B7PRA5CNFSM4KHQDJIKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEJER5JQ#issuecomment-575217318", "url": "https://github.com/sheabunge/code-snippets/issues/90?email_source=notifications\u0026email_token=AOJNKSCQXKF3IIBDX4Q5O2LQ6B7PRA5CNFSM4KHQDJIKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEJER5JQ#issuecomment-575217318", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]
 

Links:
------
[1]
https://github.com/sheabunge/code-snippets/issues/90?email_source=notifications&amp;email_token=AOJNKSCQXKF3IIBDX4Q5O2LQ6B7PRA5CNFSM4KHQDJIKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEJER5JQ#issuecomment-575217318
[2]

**Comment by sheabunge** [comment]
Hi Judy,

Here is the snippet that is included in the original version of the plugin. You can copy and paste it into a new snippet and modify as needed:

`add_action( 'wp_head', function () { ?>
<script>

// JavaScript code goes here

</script>
<?php } );`

**Comment by judy5** [comment]
Thanks, the problem why it fifnt delete properly is that in settings u
need to tick the option where it says on delete, delete all the settings
etc then it install properly again. 

Keep Well

---

-------------------------

Regards,
 Judy

 0834450940 
admin@happywebi.co.za 
http://www.happywebi.co.za/ 

On 2020-01-17 06:33, Shea Bunge wrote:

> Hi Judy, 
> 
> Here is the snippet that is included in the original version of the plugin. You can copy and paste it into a new snippet and modify as needed: 
> 
> `add_action( 'wp_head', function () { ?> <script> // JavaScript code goes here </script> 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2]. [ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/sheabunge/code-snippets/issues/90?email_source=notifications\u0026email_token=AOJNKSH2GDUTD3USEDDIJD3Q6EYJJA5CNFSM4KHQDJIKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEJGNGZA#issuecomment-575460196", "url": "https://github.com/sheabunge/code-snippets/issues/90?email_source=notifications\u0026email_token=AOJNKSH2GDUTD3USEDDIJD3Q6EYJJA5CNFSM4KHQDJIKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEJGNGZA#issuecomment-575460196", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]
 

Links:
------
[1]
https://github.com/sheabunge/code-snippets/issues/90?email_source=notifications&amp;email_token=AOJNKSH2GDUTD3USEDDIJD3Q6EYJJA5CNFSM4KHQDJIKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEJGNGZA#issuecomment-575460196
[2]

**Comment by sheabunge** [comment]
Yes, that's correct. That setting exists is to prevent people from removing the plugin and unintentionally losing all their data.
