### ISSUE TITLE
Site Crash =/

### ISSUE THREAD

**Issue by Brandog** [sheabunge/code-snippets#93]
Greetings to the creators of this wonderful plugging, it is very clean and easy to use (very useful for those who are starting)

My problem appears after placing the pixel code facebook, I got an error in that code and the page went into error. I entered recovery mode and disable the pluggin and the page already works but not the pluggin = /

I reinstalled the plug-in but when activating it the site falls again, is there a way to modify the code that I entered from the file manager? I searched but I don't get the file indicated to delete the last code added and leave all the other codes I already had.

Beforehand thank you very much!

**Comment by VerdiH** [comment]
Hi @Brandog 

We've just updated our FAQ with two potential recovery solution: [method 1](https://wordpress.org/plugins/code-snippets/#how%20can%20i%20recover%20my%20site%20if%20it%20is%20crashed%20by%20a%20buggy%20snippet%3F%20(method%20one)) and [method 2](https://wordpress.org/plugins/code-snippets/#how%20can%20i%20recover%20my%20site%20if%20it%20is%20crashed%20by%20a%20buggy%20snippet%3F%20(method%20two)). I hope this helps!

**Comment by Brandog** [comment]
Thank you very much for providing the solution so fast and for its effectiveness

Method 2 worked perfectly

Too bad, I hadn't seen it before = S had searched the forum but not there hehe.

Thanks again

**Comment by VerdiH** [comment]
Most welcome @Brandog ; )
