### ISSUE TITLE
💡 [Idea] Extend the default Gutenberg code block

### ISSUE THREAD

**Issue by pgroot91** [sheabunge/code-snippets#97]
💡 [Idea] Extend the default Gutenberg code block

How awesome would it be if you have a block section were you're able to select/find code snippets from the library and then insert them directly into the code block. This is just a quick 💡 moment.

**Comment by sheabunge** [comment]
Nice idea, we have something planned like this.

Just to check, would this be a block to insert the output of running a snippet, or to display the snippet code?

**Comment by pgroot91** [comment]
He @sheabunge, 

The idea mentioned was for simply pasting in snippets code in the code block. 

That other addition sounds awesome too 👍

**Comment by sheabunge** [comment]
We have something very similar to this planned for v3.0. Thanks for the suggestion!
