### ISSUE TITLE
Bugs with code snippets crashing whole site and slider activators bad.

### ISSUE THREAD

**Issue by akissz** [sheabunge/code-snippets#99]
If you write a code with an error or test improper code this crashes the whole website and the only way to disable the plugin is rename folder, and additionally you will need to manually edit the database to delete the bad codes. There should be a fix to solve this without going through this whole process.
Also the slider activators for each snippet in the list do not function well in my opinion. The sliders do not slide clear. Maybe the sliders need to be a little wider, or a different style all together. It visually looks nice now but it functions badly at the moment.

**Comment by sheabunge** [comment]
If you see the [Frequently Asked Questions](https://wordpress.org/plugins/code-snippets/faq/), there are multiple ways to easily temporarily deactivate all snippets without editing the database or deactivating the plugin.

Feel free to suggest alternative designs for the sliders – I'm not entirely sure how to address the points you raise. Is your main issue with the hover effect on the toggle buttons?

**Comment by sheabunge** [comment]
Closing this for now, but feel free to add your thoughts.
